; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mhetesp32devkit]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = mhetesp32devkit
framework = arduino
monitor_speed = 115200
; 採用16MB FLASH ESP32
board_upload.flash_size = 16MB
; 使用 PlatformIO 內建的 16MB 預設分割表
board_build.partitions = default_16MB.csv    
build_flags = 
    -D CORE_DEBUG_LEVEL=3 


lib_deps =
    https://github.com/Dlloydev/QuickPID.git