; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:mhetesp32devkit]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = mhetesp32devkit
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
	-D CORE_DEBUG_LEVEL=3
lib_deps =
    https://github.com/Dlloydev/QuickPID.git
    https://github.com/Dlloydev/sTune.git
	https://github.com/Dlloydev/sTune.git
